---
name: Generate enums

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  generate:
    name: Generate enums
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.3.0
      - name: 🏗 Set up Poetry
        run: pipx install poetry
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "poetry"
      - name: 🏗 Install workflow dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: 🏗 Install Python dependencies
        run: poetry install --no-interaction
      - name: ⤵️ Check out capabilities from GitHub
        uses: actions/checkout@v4.3.0
        with:
          repository: "pysmartthings/capabilities"
          path: "capabilities"
      - name: Generate
        run: python script/generate_enums.py
      - name: Run ruff
        run: poetry run ruff format src && poetry run ruff check src --fix
      - name: Remove capabilities
        run: rm -rf capabilities
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ github.head_ref }}
          title: Update capabilities
          body: Sync the capabilities with the SmartThings API
