---
name: Generate enums

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  generate:
    name: Generate enums
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.0
      - name: 🏗 Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Install Python dependencies
        run: uv sync --all-groups
      - name: ⤵️ Check out capabilities from GitHub
        uses: actions/checkout@v7.0.0
        with:
          repository: "pysmartthings/capabilities"
          path: "capabilities"
      - name: Generate
        run: uv run python script/generate_enums.py
      - name: Run ruff
        run: uv run ruff format src && uv run ruff check src --fix
      - name: Remove capabilities
        run: rm -rf capabilities
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          base: ${{ github.head_ref }}
          title: Update capabilities
          body: Sync the capabilities with the SmartThings API
